In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np

In [2]:
strat_train_set = pd.read_csv("strat_train_set.csv")
strat_test_set = pd.read_csv("strat_test_set.csv")

In [3]:
housing = strat_train_set.drop("median_house_value", axis=1)
housing_lables = strat_train_set["median_house_value"].copy()

In [4]:
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-121.46,38.52,29.0,3873.0,797.0,2237.0,706.0,2.1736,INLAND
1,-117.23,33.09,7.0,5320.0,855.0,2015.0,768.0,6.3373,NEAR OCEAN
2,-119.04,35.37,44.0,1618.0,310.0,667.0,300.0,2.8750,INLAND
3,-117.13,32.75,24.0,1877.0,519.0,898.0,483.0,2.2264,NEAR OCEAN
4,-118.70,34.28,27.0,3536.0,646.0,1837.0,580.0,4.4964,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
16507,-117.07,33.03,14.0,6665.0,1231.0,2026.0,1001.0,5.0900,<1H OCEAN
16508,-121.42,38.51,15.0,7901.0,1422.0,4769.0,1418.0,2.8139,INLAND
16509,-122.72,38.44,48.0,707.0,166.0,458.0,172.0,3.1797,<1H OCEAN
16510,-122.70,38.31,14.0,3155.0,580.0,1208.0,501.0,4.1964,<1H OCEAN
16511,-122.14,39.97,27.0,1079.0,222.0,625.0,197.0,3.1319,INLAND

In [5]:
from sklearn.impute import SimpleImputer

In [6]:
imputer = SimpleImputer(strategy = "median")

In [7]:
housing_num = housing.select_dtypes(include=[np.number])

In [8]:
housing_num

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,-121.46,38.52,29.0,3873.0,797.0,2237.0,706.0,2.1736
1,-117.23,33.09,7.0,5320.0,855.0,2015.0,768.0,6.3373
2,-119.04,35.37,44.0,1618.0,310.0,667.0,300.0,2.8750
3,-117.13,32.75,24.0,1877.0,519.0,898.0,483.0,2.2264
4,-118.70,34.28,27.0,3536.0,646.0,1837.0,580.0,4.4964
...,...,...,...,...,...,...,...,...
16507,-117.07,33.03,14.0,6665.0,1231.0,2026.0,1001.0,5.0900
16508,-121.42,38.51,15.0,7901.0,1422.0,4769.0,1418.0,2.8139
16509,-122.72,38.44,48.0,707.0,166.0,458.0,172.0,3.1797
16510,-122.70,38.31,14.0,3155.0,580.0,1208.0,501.0,4.1964
16511,-122.14,39.97,27.0,1079.0,222.0,625.0,197.0,3.1319

In [9]:
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [10]:
housing_imputed = imputer.fit_transform(housing_num)

In [11]:
housing_non = pd.DataFrame(housing_imputed,columns=housing_num.columns,index=housing_num.index)

In [12]:
housing_non.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16512 entries, 0 to 16511
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           16512 non-null  float64
 1   latitude            16512 non-null  float64
 2   housing_median_age  16512 non-null  float64
 3   total_rooms         16512 non-null  float64
 4   total_bedrooms      16512 non-null  float64
 5   population          16512 non-null  float64
 6   households          16512 non-null  float64
 7   median_income       16512 non-null  float64
dtypes: float64(8)
memory usage: 1.0 MB

In [13]:
housing_non["ocean_proximity"] = housing["ocean_proximity"]

In [14]:
housing_non

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-121.46,38.52,29.0,3873.0,797.0,2237.0,706.0,2.1736,INLAND
1,-117.23,33.09,7.0,5320.0,855.0,2015.0,768.0,6.3373,NEAR OCEAN
2,-119.04,35.37,44.0,1618.0,310.0,667.0,300.0,2.8750,INLAND
3,-117.13,32.75,24.0,1877.0,519.0,898.0,483.0,2.2264,NEAR OCEAN
4,-118.70,34.28,27.0,3536.0,646.0,1837.0,580.0,4.4964,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
16507,-117.07,33.03,14.0,6665.0,1231.0,2026.0,1001.0,5.0900,<1H OCEAN
16508,-121.42,38.51,15.0,7901.0,1422.0,4769.0,1418.0,2.8139,INLAND
16509,-122.72,38.44,48.0,707.0,166.0,458.0,172.0,3.1797,<1H OCEAN
16510,-122.70,38.31,14.0,3155.0,580.0,1208.0,501.0,4.1964,<1H OCEAN
16511,-122.14,39.97,27.0,1079.0,222.0,625.0,197.0,3.1319,INLAND

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
onehot_encoder = OneHotEncoder()

In [17]:
housing_cat = housing_non[['ocean_proximity']]
housing_cat

      ocean_proximity
0              INLAND
1          NEAR OCEAN
2              INLAND
3          NEAR OCEAN
4           <1H OCEAN
...               ...
16507       <1H OCEAN
16508          INLAND
16509       <1H OCEAN
16510       <1H OCEAN
16511          INLAND

[16512 rows x 1 columns]

In [18]:
set(housing_cat['ocean_proximity'])

{'<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'}

In [19]:
housing_cat = onehot_encoder.fit_transform(housing_cat)

In [20]:
housing_cat.toarray()

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], shape=(16512, 5))

In [21]:
housing_cat = pd.DataFrame(housing_cat.toarray(),columns=['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],index=housing_non.index)

In [22]:
housing_cat

       <1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
0            0.0     1.0     0.0       0.0         0.0
1            0.0     0.0     0.0       0.0         1.0
2            0.0     1.0     0.0       0.0         0.0
3            0.0     0.0     0.0       0.0         1.0
4            1.0     0.0     0.0       0.0         0.0
...          ...     ...     ...       ...         ...
16507        1.0     0.0     0.0       0.0         0.0
16508        0.0     1.0     0.0       0.0         0.0
16509        1.0     0.0     0.0       0.0         0.0
16510        1.0     0.0     0.0       0.0         0.0
16511        0.0     1.0     0.0       0.0         0.0

[16512 rows x 5 columns]

In [23]:
housing_non.drop("ocean_proximity",axis=1,inplace=True)

In [24]:
housing_non = pd.concat([housing_non, housing_cat], axis=1)

In [25]:
housing_non

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,-121.46,38.52,29.0,3873.0,797.0,2237.0,706.0,2.1736,0.0,1.0,0.0,0.0,0.0
1,-117.23,33.09,7.0,5320.0,855.0,2015.0,768.0,6.3373,0.0,0.0,0.0,0.0,1.0
2,-119.04,35.37,44.0,1618.0,310.0,667.0,300.0,2.8750,0.0,1.0,0.0,0.0,0.0
3,-117.13,32.75,24.0,1877.0,519.0,898.0,483.0,2.2264,0.0,0.0,0.0,0.0,1.0
4,-118.70,34.28,27.0,3536.0,646.0,1837.0,580.0,4.4964,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16507,-117.07,33.03,14.0,6665.0,1231.0,2026.0,1001.0,5.0900,1.0,0.0,0.0,0.0,0.0
16508,-121.42,38.51,15.0,7901.0,1422.0,4769.0,1418.0,2.8139,0.0,1.0,0.0,0.0,0.0
16509,-122.72,38.44,48.0,707.0,166.0,458.0,172.0,3.1797,1.0,0.0,0.0,0.0,0.0
16510,-122.70,38.31,14.0,3155.0,580.0,1208.0,501.0,4.1964,1.0,0.0,0.0,0.0,0.0
16511,-122.14,39.97,27.0,1079.0,222.0,625.0,197.0,3.1319,0.0,1.0,0.0,0.0,0.0

In [26]:
from sklearn.preprocessing import MinMaxScaler

In [28]:
min_max_scaler = MinMaxScaler(feature_range = (-1,1))

In [29]:
housing_non_minmax_scaled = min_max_scaler.fit_transform(housing_non)

In [31]:
housing_non_minmax_scaled = pd.DataFrame(housing_non_minmax_scaled,columns=housing_non.columns,index=housing_non.index)

In [32]:
housing_non_minmax_scaled

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,-0.424303,0.270988,0.098039,-0.803276,-0.743879,-0.874772,-0.737117,-0.769148,-1.0,1.0,-1.0,-1.0,-1.0
1,0.418327,-0.883103,-0.764706,-0.729664,-0.725193,-0.887217,-0.713966,-0.194852,-1.0,-1.0,-1.0,-1.0,1.0
2,0.057769,-0.398512,0.686275,-0.917994,-0.900773,-0.962779,-0.888723,-0.672405,-1.0,1.0,-1.0,-1.0,-1.0
3,0.438247,-0.955367,-0.098039,-0.904818,-0.833441,-0.949830,-0.820388,-0.761865,-1.0,-1.0,-1.0,-1.0,1.0
4,0.125498,-0.630181,0.019608,-0.820420,-0.792526,-0.897194,-0.784167,-0.448766,1.0,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16507,0.450199,-0.895855,-0.490196,-0.661240,-0.604059,-0.886600,-0.626960,-0.366891,1.0,-1.0,-1.0,-1.0,-1.0
16508,-0.416335,0.268863,-0.450980,-0.598362,-0.542526,-0.732840,-0.471247,-0.680832,-1.0,1.0,-1.0,-1.0,-1.0
16509,-0.675299,0.253985,0.843137,-0.964338,-0.947165,-0.974495,-0.936520,-0.630378,1.0,-1.0,-1.0,-1.0,-1.0
16510,-0.671315,0.226355,-0.490196,-0.839803,-0.813789,-0.932453,-0.813667,-0.490145,1.0,-1.0,-1.0,-1.0,-1.0
16511,-0.559761,0.579171,0.019608,-0.945414,-0.929124,-0.965134,-0.927184,-0.636971,-1.0,1.0,-1.0,-1.0,-1.0

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
std_scaler = StandardScaler()

In [35]:
housing_std_scaled = std_scaler.fit_transform(housing_non)

In [37]:
housing_std_scaled = pd.DataFrame(housing_std_scaled,columns=housing_non.columns,index=housing.index)

In [38]:
housing_std_scaled

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,-0.941350,1.347438,0.027564,0.584777,0.640371,0.732602,0.556286,-0.893647,-0.887683,1.46218,-0.011006,-0.354889,-0.384217
1,1.171782,-1.192440,-1.722018,1.261467,0.781561,0.533612,0.721318,1.292168,-0.887683,-0.68391,-0.011006,-0.354889,2.602693
2,0.267581,-0.125972,1.220460,-0.469773,-0.545138,-0.674675,-0.524407,-0.525434,-0.887683,1.46218,-0.011006,-0.354889,-0.384217
3,1.221738,-1.351474,-0.370069,-0.348652,-0.036367,-0.467617,-0.037297,-0.865929,-0.887683,-0.68391,-0.011006,-0.354889,2.602693
4,0.437431,-0.635818,-0.131489,0.427179,0.272790,0.374060,0.220898,0.325752,1.126529,-0.68391,-0.011006,-0.354889,-0.384217
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16507,1.251711,-1.220505,-1.165333,1.890456,1.696862,0.543471,1.341519,0.637374,1.126529,-0.68391,-0.011006,-0.354889,-0.384217
16508,-0.921368,1.342761,-1.085806,2.468471,2.161816,3.002174,2.451492,-0.557509,-0.887683,1.46218,-0.011006,-0.354889,-0.384217
16509,-1.570794,1.310018,1.538566,-0.895802,-0.895679,-0.862013,-0.865118,-0.365475,1.126529,-0.68391,-0.011006,-0.354889,-0.384217
16510,-1.560803,1.249211,-1.165333,0.249005,0.112126,-0.189747,0.010616,0.168261,1.126529,-0.68391,-0.011006,-0.354889,-0.384217
16511,-1.281050,2.025674,-0.131489,-0.721836,-0.759358,-0.712322,-0.798573,-0.390569,-0.887683,1.46218,-0.011006,-0.354889,-0.384217

In [48]:
housing_std_scaled.max()

longitude              2.630493
latitude               2.951818
housing_median_age     1.856671
total_rooms           17.161559
total_bedrooms        13.817298
population            30.711200
households            12.939008
median_income          5.839873
<1H OCEAN              1.126529
INLAND                 1.462180
ISLAND                90.857031
NEAR BAY               2.817783
NEAR OCEAN             2.602693
dtype: float64